### PR TITLE
patch-image tool needs doc cleanup and bugfixes

### PR DESCRIPTION
**Pull request by pjbreaux**
@richbrowne 

Issues: Addresses Issue #4

Problem: The patch image tool needs better functional structure and
better documentation for usage. The startup script and it's functions
need merging with those in perforce

Analysis: Added info to the main README.rst in this repo to demonstrate
usage of the patch image tool. Merged in the new startup script changes.

### CODE REVIEW

**Comment by pjbreaux** [comment]
Okay @richbrowne, this is ready for review. Two things of interest here are that we renamed the openstack-functions directory so that makes the diff much larger. The other thing is that I had to comment out this line https://github.com/F5Networks/f5-openstack-image-prep/pull/6/files#diff-6ae8da551819e2a4ad1e77da84cd0c4eR97 in the startup script because it was bailing out here on bootup.

**Comment by richbrowne** [comment]
You did a good job here Paul.  I think this is good and want to merge it, but there looks to be more opportunities to clean this up, by:

I wouldn't do these now, but:
1) Functionally combining the volume group managment.
2) Creating a main function (nice but not necessary), this could have a clear functional flow of what is going on.
3) Move all functions to the top of the file.  There is one function def that seems to be defined in the middle of the file.

**Comment by pjbreaux** [comment]
Yes, I certainly saw those, and I have a ticket to address a full refactor of this script, but I didn't want to tackle that just yet, since I would just as soon turn it into a python tool.

**Comment by pjbreaux** [comment]
I'll take care of 1 and 3 now.

**Comment by pjbreaux** [comment]
Merging. This does not fix all issues brought up by @richbrowne, but it does allow a little more flexibility and readability in the patch image tool. The patch-image tool issue will remain open.

**Pull request merged**
